<Project>
	<PropertyGroup>
		<SolutionDir>$(MSBuildThisFileDirectory)..\</SolutionDir>
		<License>MIT</License>
		<Authors>Jean-Philippe Bruyère</Authors>

		<EnableDynamicLoading>true</EnableDynamicLoading>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="$(SolutionDir)CrowEditBase\CrowEditBase.csproj" />
	</ItemGroup>
</Project>
