<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net6</TargetFrameworks>
		<EnableDefaultItems>false</EnableDefaultItems>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="src\**\*.cs" />
		<EmbeddedResource Include="ui\**\*.*" />
		<EmbeddedResource Include="default.conf" />
		<None Include="CERoslynPlugin.targets" >
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Enums.NET" Version="4.0.0" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Build" Version="15.1.*" ExcludeAssets="runtime" />
		<PackageReference Include="Microsoft.Build.Runtime" Version="15.1.*" ExcludeAssets="runtime" />
		<!--<PackageReference Include="Microsoft.Build.Tasks.Core" Version="15.1.*"/>    -->
		<PackageReference Include="Microsoft.Build.Utilities.Core" Version="15.1.*" ExcludeAssets="runtime" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.3.*" >
			<IncludeAssets>all</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>runtime</ExcludeAssets>
			<Visible>False</Visible>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.*" >
			<IncludeAssets>all</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>runtime</ExcludeAssets>
			<Visible>False</Visible>
		</PackageReference>
	</ItemGroup>




</Project>
