<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net6</TargetFrameworks>
		<EnableDefaultItems>false</EnableDefaultItems>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="src\**\*.cs" />
		<EmbeddedResource Include="ui\**\*.*" Exclude="ui\DefaultTemplateOverrides\*.*">
			<LogicalName>ui.%(Filename)%(Extension)</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="ui\DefaultTemplateOverrides\*.template">
			<LogicalName>Crow.%(Filename).template</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="icons\**\*.*">
			<LogicalName>icons.%(Filename)%(Extension)</LogicalName>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="/mnt/sdata/devel/crow/Crow/Crow.csproj"/>
		<!--<PackageReference Include="Crow" Version="1.3.2-beta" />-->
		<PackageReference Include="Crow.CairoBackend" Version="1.2.4-beta" />
	</ItemGroup>
	<ItemGroup>
		<AssemblyAttribute Include="Crow.CrowAssemblyPriority">
			<_Parameter1>0</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>	
</Project>
